
import { City, CityStatus, Mesorregion } from '../types';

export const internalCitiesData: City[] = [
  // --- Cidades Consolidadas (Base Original + Novas) ---
  {
    id: 5103403,
    name: 'Cuiabá',
    population: 650912,
    population15to44: 273383,
    averageIncome: 3500,
    urbanizationIndex: 0.98,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'cuiabano',
    anniversary: '8 de abril',
    mayor: 'Abilio Jacques Brunini Moumer',
    monthlyRevenue: 215000,
    implementationStartDate: '2022-08-01',
    averageFormalSalary: 3960,
    formalJobs: 236759,
    urbanizedAreaKm2: 155,
  },
  {
    id: 5108402,
    name: 'Várzea Grande',
    population: 299472,
    population15to44: 125778,
    averageIncome: 2800,
    urbanizationIndex: 0.95,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'várzea-grandense',
    anniversary: '15 de maio',
    mayor: 'Flavia Petersen Moretti De Araujo',
    monthlyRevenue: 98250,
    implementationStartDate: '2023-01-15',
    averageFormalSalary: 2750,
    formalJobs: 64888,
    urbanizedAreaKm2: 85,
  },
  {
    id: 5107602,
    name: 'Rondonópolis',
    population: 244897,
    population15to44: 102857,
    averageIncome: 3200,
    urbanizationIndex: 0.96,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'rondonopolitano',
    anniversary: '10 de dezembro',
    mayor: 'Claudio Ferreira De Souza',
    monthlyRevenue: 85400,
    implementationStartDate: '2023-06-10',
    averageFormalSalary: 3300,
    formalJobs: 70891,
    urbanizedAreaKm2: 70,
  },
  {
    id: 5107909,
    name: 'Sinop',
    population: 196067,
    population15to44: 82348,
    averageIncome: 4100,
    urbanizationIndex: 0.92,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'sinopense',
    anniversary: '14 de setembro',
    mayor: 'Roberto Dorner',
    monthlyRevenue: 92100,
    implementationStartDate: '2023-09-15',
    averageFormalSalary: 3190,
    formalJobs: 56128,
    urbanizedAreaKm2: 65,
  },
  {
    id: 5107925,
    name: 'Sorriso',
    population: 110635,
    population15to44: 46467,
    averageIncome: 4500,
    urbanizationIndex: 0.89,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'sorrisense',
    anniversary: '13 de maio',
    mayor: 'Alei Fernandes',
    monthlyRevenue: 58900,
    implementationStartDate: '2023-11-20',
    averageFormalSalary: 3410,
    formalJobs: 41753,
    urbanizedAreaKm2: 50,
  },
  {
    id: 5105150,
    name: 'Lucas do Rio Verde',
    population: 83798,
    population15to44: 35195,
    averageIncome: 4200,
    urbanizationIndex: 0.90,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'luverdense',
    anniversary: '5 de agosto',
    mayor: 'Miguel Vaz Ribeiro',
    monthlyRevenue: 42300,
    implementationStartDate: '2024-01-05',
    averageFormalSalary: 3350,
    formalJobs: 34500,
    urbanizedAreaKm2: 45,
  },

  // --- Cidades em Expansão (Novas Adições) ---
  {
    id: 5107941,
    name: 'Tangará da Serra',
    population: 106950,
    population15to44: 44919,
    averageIncome: 3100,
    urbanizationIndex: 0.91,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'tangaraense',
    anniversary: '13 de maio',
    mayor: 'Vander Alberto Masson',
    implementationStartDate: '2024-08-01',
    averageFormalSalary: 2800,
    formalJobs: 35120,
    urbanizedAreaKm2: 48,
  },
  {
    id: 5107206,
    name: 'Primavera do Leste',
    population: 85146,
    population15to44: 35761,
    averageIncome: 3800,
    urbanizationIndex: 0.93,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'primaverense',
    anniversary: '13 de maio',
    mayor: 'Sergio Machnic',
    implementationStartDate: '2024-09-10',
    averageFormalSalary: 3100,
    formalJobs: 30100,
    urbanizedAreaKm2: 40,
  },
  {
    id: 5106224,
    name: 'Nova Mutum',
    population: 55430,
    population15to44: 23281,
    averageIncome: 4300,
    urbanizationIndex: 0.91,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'mutuense',
    anniversary: '4 de julho',
    mayor: 'Leandro Felix Pereira',
    implementationStartDate: '2024-10-01',
    averageFormalSalary: 3400,
    formalJobs: 25600,
    urbanizedAreaKm2: 38,
  },
  {
    id: 5102504,
    name: 'Cáceres',
    population: 95448,
    population15to44: 40088,
    averageIncome: 2700,
    urbanizationIndex: 0.88,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'cacerense',
    anniversary: '6 de outubro',
    mayor: 'Antônia Eliene Liberato Dias',
    implementationStartDate: '2024-10-15',
    averageFormalSalary: 2580,
    formalJobs: 21500,
    urbanizedAreaKm2: 42,
  },
  {
    id: 5102637,
    name: 'Campo Novo do Parecis',
    population: 45759,
    population15to44: 19219,
    averageIncome: 3500,
    urbanizationIndex: 0.88,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'campo-novense',
    anniversary: '4 de julho',
    mayor: 'Edilson Antonio Piaia',
    implementationStartDate: '2024-11-01',
    averageFormalSalary: 3200,
    formalJobs: 15000,
    urbanizedAreaKm2: 28,
  },

  // --- Cidades em Planejamento (Base Original + Novas) ---
  {
    id: 5101803,
    name: 'Barra do Garças',
    population: 69210,
    population15to44: 29068,
    averageIncome: 2900,
    urbanizationIndex: 0.94,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'barra-garcense',
    anniversary: '15 de setembro',
    mayor: 'Adilson Gonçalves De Macedo',
    averageFormalSalary: 2650,
    formalJobs: 18430,
    urbanizedAreaKm2: 35,
  },
  {
    id: 5102678,
    name: 'Campo Verde',
    population: 44585,
    population15to44: 18726,
    averageIncome: 3300,
    urbanizationIndex: 0.87,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'campo-verdense',
    anniversary: '4 de julho',
    mayor: 'Alexandre Lopes De Oliveira',
    averageFormalSalary: 3000,
    formalJobs: 14500,
    urbanizedAreaKm2: 27,
  },
  {
    id: 5105101,
    name: 'Juína',
    population: 47201,
    population15to44: 19824,
    averageIncome: 2800,
    urbanizationIndex: 0.86,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'juinense',
    anniversary: '9 de maio',
    mayor: 'Paulo Augusto Veronese',
    averageFormalSalary: 2600,
    formalJobs: 12000,
    urbanizedAreaKm2: 29,
  },
  {
    id: 5100250,
    name: 'Alta Floresta',
    population: 58896,
    population15to44: 24736,
    averageIncome: 3000,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'alta-florestense',
    anniversary: '19 de maio',
    mayor: 'Valdemar Gamba',
    averageFormalSalary: 2700,
    formalJobs: 15800,
    urbanizedAreaKm2: 30,
  },
  {
    id: 5106828,
    name: 'Pontes e Lacerda',
    population: 50403,
    population15to44: 21169,
    averageIncome: 2700,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'lacerdense',
    anniversary: '30 de dezembro',
    mayor: 'Jakson Francisco Bassi',
    averageFormalSalary: 2500,
    formalJobs: 12000,
    urbanizedAreaKm2: 30,
  },
  {
    id: 5104104,
    name: 'Guarantã do Norte',
    population: 31920,
    population15to44: 13406,
    averageIncome: 2800,
    urbanizationIndex: 0.84,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'guarantãense',
    anniversary: '2 de junho',
    mayor: 'Alberto Márcio Gonçalves',
    averageFormalSalary: 2550,
    formalJobs: 7900,
    urbanizedAreaKm2: 22,
  },
  {
    id: 5106455,
    name: 'Peixoto de Azevedo',
    population: 32712,
    population15to44: 13739,
    averageIncome: 2800,
    urbanizationIndex: 0.83,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'peixotense',
    anniversary: '13 de maio',
    mayor: 'Nilmar Nunes De Miranda',
    averageFormalSalary: 2600,
    formalJobs: 8000,
    urbanizedAreaKm2: 21,
  },

  // --- Demais Cidades de Mato Grosso (Algumas selecionadas para contexto) ---
  
  {
    id: 5100102,
    name: 'Acorizal',
    population: 5014,
    population15to44: 2105,
    averageIncome: 2300,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'acorizalense',
    anniversary: '12 de dezembro',
    mayor: 'Diego Ewerton Figueiredo Taques',
    averageFormalSalary: 2100,
    formalJobs: 800,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5100201,
    name: 'Água Boa',
    population: 29210,
    population15to44: 12268,
    averageIncome: 3100,
    urbanizationIndex: 0.88,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'água-boense',
    anniversary: '9 de julho',
    mayor: 'Mariano Kolankiewicz Filho',
    averageFormalSalary: 2850,
    formalJobs: 7800,
    urbanizedAreaKm2: 25,
  },
  {
    id: 5100300,
    name: 'Alto Araguaia',
    population: 17192,
    population15to44: 7220,
    averageIncome: 2900,
    urbanizationIndex: 0.89,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'araguaiense',
    anniversary: '26 de outubro',
    mayor: 'Jacson Marlon Niedermeier',
    averageFormalSalary: 2700,
    formalJobs: 4500,
    urbanizedAreaKm2: 15,
  },
  {
    id: 5100359,
    name: 'Alto Boa Vista',
    population: 6867,
    population15to44: 2884,
    averageIncome: 2400,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'alto-boa-vistense',
    anniversary: '13 de maio',
    mayor: 'José Pereira Maranhão',
    averageFormalSalary: 2200,
    formalJobs: 1200,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5100409,
    name: 'Alto Garças',
    population: 13051,
    population15to44: 5481,
    averageIncome: 2800,
    urbanizationIndex: 0.82,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'alto-garcense',
    anniversary: '10 de dezembro',
    mayor: 'Cezalpino Mendes Teixeira Junior',
    averageFormalSalary: 2500,
    formalJobs: 3800,
    urbanizedAreaKm2: 12,
  },
  {
    id: 5100508,
    name: 'Alto Paraguai',
    population: 8007,
    population15to44: 3362,
    averageIncome: 2300,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'alto-paraguaiense',
    anniversary: '16 de dezembro',
    mayor: 'Adair Jose Alves Moreira',
    averageFormalSalary: 2150,
    formalJobs: 1500,
    urbanizedAreaKm2: 7,
  },
  {
    id: 5100607,
    name: 'Alto Taquari',
    population: 10976,
    population15to44: 4609,
    averageIncome: 3500,
    urbanizationIndex: 0.90,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'taquariense',
    anniversary: '13 de maio',
    mayor: 'Marilda Garofolo Sperandio',
    averageFormalSalary: 3100,
    formalJobs: 4200,
    urbanizedAreaKm2: 10,
  },
  {
    id: 5101407,
    name: 'Apiacás',
    population: 10203,
    population15to44: 4285,
    averageIncome: 2600,
    urbanizationIndex: 0.72,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'apiaquense',
    anniversary: '6 de junho',
    mayor: 'Julio Cesar Dos Santos',
    averageFormalSalary: 2400,
    formalJobs: 2500,
    urbanizedAreaKm2: 11,
  },
  {
    id: 5101001,
    name: 'Aripuanã',
    population: 23049,
    population15to44: 9681,
    averageIncome: 2600,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'aripuanense',
    anniversary: '31 de dezembro',
    mayor: 'Seluir Peixer Reghin',
    averageFormalSalary: 2400,
    formalJobs: 5200,
    urbanizedAreaKm2: 18,
  },
  {
    id: 5101209,
    name: 'Araguaiana',
    population: 3223,
    population15to44: 1353,
    averageIncome: 2200,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'araguaianense',
    anniversary: '13 de maio',
    mayor: 'Jose Marra Nery',
    averageFormalSalary: 2050,
    formalJobs: 600,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5101258,
    name: 'Araguainha',
    population: 1010,
    population15to44: 424,
    averageIncome: 2100,
    urbanizationIndex: 0.60,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'araguainhense',
    anniversary: '24 de fevereiro',
    mayor: 'Francisco Gonçalves Naves',
    averageFormalSalary: 2000,
    formalJobs: 300,
    urbanizedAreaKm2: 2,
  },
  {
    id: 5101704,
    name: 'Araputanga',
    population: 16183,
    population15to44: 6797,
    averageIncome: 2700,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'araputanguense',
    anniversary: '23 de maio',
    mayor: 'Enilson De Araujo Rios',
    averageFormalSalary: 2500,
    formalJobs: 3900,
    urbanizedAreaKm2: 14,
  },
  {
    id: 5101308,
    name: 'Arenápolis',
    population: 9940,
    population15to44: 4174,
    averageIncome: 2400,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'arenapolitano',
    anniversary: '13 de maio',
    mayor: 'Ederson Figueiredo',
    averageFormalSalary: 2200,
    formalJobs: 2100,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5101902,
    name: 'Barão de Melgaço',
    population: 7488,
    population15to44: 3145,
    averageIncome: 2200,
    urbanizationIndex: 0.60,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'barão-melgacense',
    anniversary: '12 de março',
    mayor: 'Margareth Gonçalves Da Silva',
    averageFormalSalary: 2100,
    formalJobs: 1500,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5101605,
    name: 'Barra do Bugres',
    population: 29843,
    population15to44: 12534,
    averageIncome: 2800,
    urbanizationIndex: 0.88,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'barrense',
    anniversary: '19 de abril',
    mayor: 'Maria Azenilda Pereira',
    averageFormalSalary: 2600,
    formalJobs: 7500,
    urbanizedAreaKm2: 20,
  },
  {
    id: 5101852,
    name: 'Bom Jesus do Araguaia',
    population: 6830,
    population15to44: 2868,
    averageIncome: 2500,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'bonjesuense',
    anniversary: '20 de setembro',
    mayor: 'Marcilei Alves De Oliveira',
    averageFormalSalary: 2300,
    formalJobs: 1500,
    urbanizedAreaKm2: 7,
  },
  {
    id: 5102603,
    name: 'Brasnorte',
    population: 19934,
    population15to44: 8372,
    averageIncome: 2900,
    urbanizationIndex: 0.81,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'brasnortense',
    anniversary: '2 de junho',
    mayor: 'Edelo Marcelo Ferrari',
    averageFormalSalary: 2700,
    formalJobs: 4800,
    urbanizedAreaKm2: 17,
  },
  {
    id: 5102603,
    name: 'Campinápolis',
    population: 16223,
    population15to44: 6813,
    averageIncome: 2300,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'campinapolense',
    anniversary: '13 de maio',
    mayor: 'Jeovan Faria',
    averageFormalSalary: 2150,
    formalJobs: 2500,
    urbanizedAreaKm2: 10,
  },
  {
    id: 5102686,
    name: 'Campos de Júlio',
    population: 7246,
    population15to44: 3043,
    averageIncome: 3600,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'juliense',
    anniversary: '28 de novembro',
    mayor: 'Irineu Marcos Parmeggiani',
    averageFormalSalary: 3100,
    formalJobs: 2800,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5102694,
    name: 'Canabrava do Norte',
    population: 4768,
    population15to44: 2002,
    averageIncome: 2300,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'canabravense',
    anniversary: '19 de dezembro',
    mayor: 'Neuilson Da Silva Lima',
    averageFormalSalary: 2100,
    formalJobs: 800,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5102702,
    name: 'Canarana',
    population: 25843,
    population15to44: 10854,
    averageIncome: 3000,
    urbanizationIndex: 0.86,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'canaranense',
    anniversary: '15 de fevereiro',
    mayor: 'Vilson Biguelini',
    averageFormalSalary: 2800,
    formalJobs: 6500,
    urbanizedAreaKm2: 20,
  },
  {
    id: 5102793,
    name: 'Carlinda',
    population: 10328,
    population15to44: 4337,
    averageIncome: 2600,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'carlindense',
    anniversary: '19 de dezembro',
    mayor: 'Fernando De Oliveira Ribeiro',
    averageFormalSalary: 2400,
    formalJobs: 1800,
    urbanizedAreaKm2: 9,
  },
  {
    id: 5102850,
    name: 'Castanheira',
    population: 8231,
    population15to44: 3457,
    averageIncome: 2500,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'castanheirense',
    anniversary: '4 de julho',
    mayor: 'Jakson De Oliveira Rios Junior',
    averageFormalSalary: 2300,
    formalJobs: 1600,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5103007,
    name: 'Chapada dos Guimarães',
    population: 18806,
    population15to44: 7898,
    averageIncome: 2700,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'chapadense',
    anniversary: '31 de julho',
    mayor: 'Osmar Froner De Mello',
    averageFormalSalary: 2400,
    formalJobs: 3500,
    urbanizedAreaKm2: 14,
  },
  {
    id: 5103056,
    name: 'Cláudia',
    population: 12229,
    population15to44: 5136,
    averageIncome: 2800,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'claudiense',
    anniversary: '4 de julho',
    mayor: 'Marcos Fernando Feldhaus',
    averageFormalSalary: 2600,
    formalJobs: 2800,
    urbanizedAreaKm2: 10,
  },
  {
    id: 5103106,
    name: 'Cocalinho',
    population: 6220,
    population15to44: 2612,
    averageIncome: 2400,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'cocalinhense',
    anniversary: '13 de maio',
    mayor: 'Márcio Conceição Nunes De Aguiar',
    averageFormalSalary: 2200,
    formalJobs: 1100,
    urbanizedAreaKm2: 7,
  },
  {
    id: 5103205,
    name: 'Colíder',
    population: 31448,
    population15to44: 13208,
    averageIncome: 2900,
    urbanizationIndex: 0.87,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'colidense',
    anniversary: '18 de dezembro',
    mayor: 'Rodrigo Luiz Benassi',
    averageFormalSalary: 2600,
    formalJobs: 8200,
    urbanizedAreaKm2: 20,
  },
  {
    id: 5103254,
    name: 'Colniza',
    population: 41065,
    population15to44: 17247,
    averageIncome: 2400,
    urbanizationIndex: 0.68,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'colnizense',
    anniversary: '26 de novembro',
    mayor: 'Milton De Souza Amorim',
    averageFormalSalary: 2200,
    formalJobs: 6100,
    urbanizedAreaKm2: 15,
  },
  {
    id: 5103304,
    name: 'Comodoro',
    population: 21386,
    population15to44: 8982,
    averageIncome: 2800,
    urbanizationIndex: 0.82,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'comodorense',
    anniversary: '13 de maio',
    mayor: 'Rogerio Vilela Victor De Oliveira',
    averageFormalSalary: 2650,
    formalJobs: 6000,
    urbanizedAreaKm2: 18,
  },
  {
    id: 5103353,
    name: 'Confresa',
    population: 35075,
    population15to44: 14732,
    averageIncome: 2700,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'confresense',
    anniversary: '20 de dezembro',
    mayor: 'Ricardo Aloisio Babinski',
    averageFormalSalary: 2500,
    formalJobs: 8000,
    urbanizedAreaKm2: 22,
  },
  {
    id: 5103361,
    name: 'Conquista d\'Oeste',
    population: 3848,
    population15to44: 1616,
    averageIncome: 2300,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'conquistense',
    anniversary: '19 de dezembro',
    mayor: 'Odair Jose Vargas',
    averageFormalSalary: 2150,
    formalJobs: 700,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5103379,
    name: 'Cotriguaçu',
    population: 20245,
    population15to44: 8503,
    averageIncome: 2500,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'cotriguaçuense',
    anniversary: '19 de dezembro',
    mayor: 'Moises Ferreira De Jesus',
    averageFormalSalary: 2300,
    formalJobs: 4100,
    urbanizedAreaKm2: 12,
  },
  {
    id: 5103437,
    name: 'Curvelândia',
    population: 4893,
    population15to44: 2055,
    averageIncome: 2400,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'curvelandense',
    anniversary: '19 de dezembro',
    mayor: 'Jadilson Alves De Souza',
    averageFormalSalary: 2200,
    formalJobs: 900,
    urbanizedAreaKm2: 6,
  },
  {
    id: 5103452,
    name: 'Denise',
    population: 8527,
    population15to44: 3581,
    averageIncome: 2500,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'denisiense',
    anniversary: '13 de maio',
    mayor: 'Aldecir De Sousa Oliveira',
    averageFormalSalary: 2300,
    formalJobs: 1700,
    urbanizedAreaKm2: 7,
  },
  {
    id: 5103502,
    name: 'Diamantino',
    population: 22268,
    population15to44: 9353,
    averageIncome: 3200,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'diamantinense',
    anniversary: '18 de setembro',
    mayor: 'Francisco Ferreira Mendes Junior',
    averageFormalSalary: 2900,
    formalJobs: 5900,
    urbanizedAreaKm2: 19,
  },
  {
    id: 5103601,
    name: 'Dom Aquino',
    population: 7851,
    population15to44: 3297,
    averageIncome: 2300,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'dom-aquinense',
    anniversary: '14 de dezembro',
    mayor: 'Carlos Alberto Da Costa',
    averageFormalSalary: 2150,
    formalJobs: 1800,
    urbanizedAreaKm2: 9,
  },
  {
    id: 5103858,
    name: 'Feliz Natal',
    population: 14911,
    population15to44: 6263,
    averageIncome: 3300,
    urbanizationIndex: 0.79,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'feliz-natalense',
    anniversary: '17 de novembro',
    mayor: 'Jose Antonio Dubiella',
    averageFormalSalary: 3000,
    formalJobs: 4000,
    urbanizedAreaKm2: 14,
  },
  {
    id: 5103908,
    name: 'Figueirópolis d\'Oeste',
    population: 3492,
    population15to44: 1466,
    averageIncome: 2200,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'figueiropolense',
    anniversary: '19 de dezembro',
    mayor: 'Ademir Felicio Garcia',
    averageFormalSalary: 2050,
    formalJobs: 600,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5103957,
    name: 'Gaúcha do Norte',
    population: 8632,
    population15to44: 3625,
    averageIncome: 2900,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'gaucho-nortense',
    anniversary: '17 de novembro',
    mayor: 'Ari Do Prado',
    averageFormalSalary: 2700,
    formalJobs: 2100,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5103957,
    name: 'General Carneiro',
    population: 6023,
    population15to44: 2529,
    averageIncome: 2400,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'carneirense',
    anniversary: '10 de dezembro',
    mayor: 'João Filho Marques Rodrigues',
    averageFormalSalary: 2200,
    formalJobs: 1100,
    urbanizedAreaKm2: 6,
  },
  {
    id: 5104203,
    name: 'Glória d\'Oeste',
    population: 2999,
    population15to44: 1259,
    averageIncome: 2200,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'gloriense',
    anniversary: '19 de dezembro',
    mayor: 'Gheysa Maria Bonfim Borgato',
    averageFormalSalary: 2050,
    formalJobs: 400,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5104500,
    name: 'Guiratinga',
    population: 13954,
    population15to44: 5860,
    averageIncome: 2600,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'guiratinguense',
    anniversary: '2 de agosto',
    mayor: 'Waldeci Barga Rosa',
    averageFormalSalary: 2400,
    formalJobs: 2900,
    urbanizedAreaKm2: 11,
  },
  {
    id: 5104526,
    name: 'Indiavaí',
    population: 2686,
    population15to44: 1128,
    averageIncome: 2100,
    urbanizationIndex: 0.60,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'indiavaiense',
    anniversary: '19 de dezembro',
    mayor: 'Sidnei Marques Lopes',
    averageFormalSalary: 2000,
    formalJobs: 400,
    urbanizedAreaKm2: 3,
  },
  {
    id: 5104542,
    name: 'Ipiranga do Norte',
    population: 7856,
    population15to44: 3299,
    averageIncome: 4100,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'ipiranguense',
    anniversary: '29 de março',
    mayor: 'Juliano Berticelli',
    averageFormalSalary: 3800,
    formalJobs: 3100,
    urbanizedAreaKm2: 9,
  },
  {
    id: 5104543,
    name: 'Itanhangá',
    population: 7192,
    population15to44: 3020,
    averageIncome: 3000,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'itanhanguense',
    anniversary: '29 de março',
    mayor: 'Emerson Sabatine',
    averageFormalSalary: 2800,
    formalJobs: 2200,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5104526,
    name: 'Itaúba',
    population: 4668,
    population15to44: 1960,
    averageIncome: 2800,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'itaubense',
    anniversary: '13 de maio',
    mayor: 'Antonio Ferreira De Oliveira Neto',
    averageFormalSalary: 2600,
    formalJobs: 1100,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5104600,
    name: 'Itiquira',
    population: 13914,
    population15to44: 5844,
    averageIncome: 2900,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'itiquirense',
    anniversary: '1 de dezembro',
    mayor: 'Fabiano Dalla Valle',
    averageFormalSalary: 2750,
    formalJobs: 3800,
    urbanizedAreaKm2: 12,
  },
  {
    id: 5104609,
    name: 'Jaciara',
    population: 28569,
    population15to44: 11999,
    averageIncome: 2600,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'jaciarense',
    anniversary: '21 de outubro',
    mayor: 'Andreia Wagner',
    averageFormalSalary: 2450,
    formalJobs: 7500,
    urbanizedAreaKm2: 20,
  },
  {
    id: 5104807,
    name: 'Jangada',
    population: 7468,
    population15to44: 3137,
    averageIncome: 2200,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'jangadense',
    anniversary: '15 de setembro',
    mayor: 'Rogério De Oliveira Meira',
    averageFormalSalary: 2050,
    formalJobs: 1500,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5104559,
    name: 'Jauru',
    population: 8366,
    population15to44: 3514,
    averageIncome: 2500,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'jauruense',
    anniversary: '20 de dezembro',
    mayor: 'Valdeci José De Souza',
    averageFormalSalary: 2300,
    formalJobs: 2100,
    urbanizedAreaKm2: 10,
  },
  {
    id: 5105002,
    name: 'Juara',
    population: 34920,
    population15to44: 14666,
    averageIncome: 2800,
    urbanizationIndex: 0.83,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'juarense',
    anniversary: '14 de dezembro',
    mayor: 'Valdinei Holanda Moraes',
    averageFormalSalary: 2600,
    formalJobs: 8500,
    urbanizedAreaKm2: 24,
  },
  {
    id: 5105175,
    name: 'Juruena',
    population: 15637,
    population15to44: 6567,
    averageIncome: 2600,
    urbanizationIndex: 0.68,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'juruenense',
    anniversary: '4 de julho',
    mayor: 'Manoel Gontijo De Carvalho',
    averageFormalSalary: 2400,
    formalJobs: 3200,
    urbanizedAreaKm2: 13,
  },
  {
    id: 5105234,
    name: 'Juscimeira',
    population: 11438,
    population15to44: 4804,
    averageIncome: 2400,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'juscimeirense',
    anniversary: '10 de dezembro',
    mayor: 'Alexandre Russi',
    averageFormalSalary: 2250,
    formalJobs: 2900,
    urbanizedAreaKm2: 11,
  },
  {
    id: 5105259,
    name: 'Lambari d\'Oeste',
    population: 6253,
    population15to44: 2626,
    averageIncome: 2400,
    urbanizationIndex: 0.78,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'lambariense',
    anniversary: '19 de dezembro',
    mayor: 'Marcelo Vieira Vitorazzi',
    averageFormalSalary: 2200,
    formalJobs: 1300,
    urbanizedAreaKm2: 7,
  },
  {
    id: 5105309,
    name: 'Luciara',
    population: 2068,
    population15to44: 868,
    averageIncome: 2100,
    urbanizationIndex: 0.55,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'luciarense',
    anniversary: '13 de maio',
    mayor: 'Parassu De Souza Freitas',
    averageFormalSalary: 2000,
    formalJobs: 400,
    urbanizedAreaKm2: 3,
  },
  {
    id: 5105503,
    name: 'Marcelândia',
    population: 10422,
    population15to44: 4377,
    averageIncome: 2700,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'marcelandense',
    anniversary: '13 de maio',
    mayor: 'Celso Luiz Padovani',
    averageFormalSalary: 2500,
    formalJobs: 2800,
    urbanizedAreaKm2: 9,
  },
  {
    id: 5105586,
    name: 'Matupá',
    population: 17135,
    population15to44: 7197,
    averageIncome: 2900,
    urbanizationIndex: 0.84,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'matupaense',
    anniversary: '4 de julho',
    mayor: 'Bruno Santos Mena',
    averageFormalSalary: 2700,
    formalJobs: 4500,
    urbanizedAreaKm2: 14,
  },
  {
    id: 5105606,
    name: 'Mirassol d\'Oeste',
    population: 26785,
    population15to44: 11250,
    averageIncome: 2600,
    urbanizationIndex: 0.87,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'mirassolense',
    anniversary: '13 de maio',
    mayor: 'Hector Alvares Bezerra',
    averageFormalSalary: 2450,
    formalJobs: 6800,
    urbanizedAreaKm2: 21,
  },
  {
    id: 5105903,
    name: 'Nobres',
    population: 15012,
    population15to44: 6305,
    averageIncome: 2600,
    urbanizationIndex: 0.83,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'nobrense',
    anniversary: '1 de maio',
    mayor: 'Jose Domingos Fraga Filho',
    averageFormalSalary: 2400,
    formalJobs: 3500,
    urbanizedAreaKm2: 13,
  },
  {
    id: 5106158,
    name: 'Nortelândia',
    population: 5236,
    population15to44: 2199,
    averageIncome: 2500,
    urbanizationIndex: 0.89,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'nortelandense',
    anniversary: '6 de fevereiro',
    mayor: 'Mariano Gomes Miranda',
    averageFormalSalary: 2350,
    formalJobs: 1300,
    urbanizedAreaKm2: 9,
  },
  {
    id: 5106174,
    name: 'Nossa Senhora do Livramento',
    population: 12940,
    population15to44: 5434,
    averageIncome: 2300,
    urbanizationIndex: 0.60,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'livramentense',
    anniversary: '21 de maio',
    mayor: 'Thiago Gonçalo Lunguinho De Almeida',
    averageFormalSalary: 2100,
    formalJobs: 2100,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5106208,
    name: 'Nova Bandeirantes',
    population: 15330,
    population15to44: 6439,
    averageIncome: 2700,
    urbanizationIndex: 0.72,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'nova-bandeirantense',
    anniversary: '11 de agosto',
    mayor: 'João Rogério De Souza',
    averageFormalSalary: 2500,
    formalJobs: 3500,
    urbanizedAreaKm2: 13,
  },
  {
    id: 5106216,
    name: 'Nova Brasilândia',
    population: 3823,
    population15to44: 1605,
    averageIncome: 2200,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'brasilandense',
    anniversary: '19 de dezembro',
    mayor: 'José Antônio Domingos Cardoso',
    averageFormalSalary: 2050,
    formalJobs: 700,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5106182,
    name: 'Nova Canaã do Norte',
    population: 12750,
    population15to44: 5355,
    averageIncome: 2800,
    urbanizationIndex: 0.78,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'nova-canaaense',
    anniversary: '13 de maio',
    mayor: 'Allison Vinicius Oliveira Da Silva',
    averageFormalSalary: 2600,
    formalJobs: 3100,
    urbanizedAreaKm2: 12,
  },
  {
    id: 5106232,
    name: 'Nova Guarita',
    population: 4506,
    population15to44: 1892,
    averageIncome: 2500,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'nova-guaritense',
    anniversary: '13 de maio',
    mayor: 'Edson Gonzaga Ribeiro',
    averageFormalSalary: 2300,
    formalJobs: 900,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5106240,
    name: 'Nova Lacerda',
    population: 6681,
    population15to44: 2806,
    averageIncome: 2600,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'nova-lacerdense',
    anniversary: '13 de maio',
    mayor: 'Airton Justino Do Nascimento',
    averageFormalSalary: 2400,
    formalJobs: 1400,
    urbanizedAreaKm2: 6,
  },
  {
    id: 5106257,
    name: 'Nova Marilândia',
    population: 2951,
    population15to44: 1239,
    averageIncome: 2400,
    urbanizationIndex: 0.78,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'nova-marilandense',
    anniversary: '19 de dezembro',
    mayor: 'Jefferson Nogueira Souto',
    averageFormalSalary: 2200,
    formalJobs: 600,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5106265,
    name: 'Nova Maringá',
    population: 10452,
    population15to44: 4389,
    averageIncome: 2800,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'nova-maringuense',
    anniversary: '19 de dezembro',
    mayor: 'Ana Maria Urquiza Casagrande',
    averageFormalSalary: 2600,
    formalJobs: 2500,
    urbanizedAreaKm2: 9,
  },
  {
    id: 5106273,
    name: 'Nova Monte Verde',
    population: 8531,
    population15to44: 3583,
    averageIncome: 2600,
    urbanizationIndex: 0.72,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'monte-verdense',
    anniversary: '19 de dezembro',
    mayor: 'Edemilson Marino Dos Santos',
    averageFormalSalary: 2400,
    formalJobs: 1900,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5106281,
    name: 'Nova Nazaré',
    population: 4200,
    population15to44: 1764,
    averageIncome: 2300,
    urbanizationIndex: 0.60,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'nova-nazareense',
    anniversary: '19 de dezembro',
    mayor: 'Reginaldo Martins Del Colle',
    averageFormalSalary: 2100,
    formalJobs: 700,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5106299,
    name: 'Nova Olímpia',
    population: 18128,
    population15to44: 7614,
    averageIncome: 2900,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'nova-olimpiense',
    anniversary: '13 de maio',
    mayor: 'Ari Candido Batista',
    averageFormalSalary: 2750,
    formalJobs: 4500,
    urbanizedAreaKm2: 16,
  },
  {
    id: 5106190,
    name: 'Nova Santa Helena',
    population: 3482,
    population15to44: 1462,
    averageIncome: 2400,
    urbanizationIndex: 0.68,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'santa-helenense',
    anniversary: '13 de maio',
    mayor: 'Paulinho Bortolini',
    averageFormalSalary: 2200,
    formalJobs: 600,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5106289,
    name: 'Nova Ubiratã',
    population: 11520,
    population15to44: 4838,
    averageIncome: 3500,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'ubiratãense',
    anniversary: '19 de dezembro',
    mayor: 'Edegar José Bernardi',
    averageFormalSalary: 3200,
    formalJobs: 4500,
    urbanizedAreaKm2: 10,
  },
  {
    id: 5106273,
    name: 'Nova Xavantina',
    population: 20172,
    population15to44: 8472,
    averageIncome: 2700,
    urbanizationIndex: 0.90,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'nova-xavantinense',
    anniversary: '13 de maio',
    mayor: 'João Machado Neto',
    averageFormalSalary: 2550,
    formalJobs: 5100,
    urbanizedAreaKm2: 18,
  },
  {
    id: 5106307,
    name: 'Novo Horizonte do Norte',
    population: 3349,
    population15to44: 1406,
    averageIncome: 2400,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'novo-horizontino',
    anniversary: '13 de maio',
    mayor: 'Agenor Evangelista Da Silva Junior',
    averageFormalSalary: 2200,
    formalJobs: 600,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5106240,
    name: 'Novo Mundo',
    population: 9382,
    population15to44: 3940,
    averageIncome: 2600,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'novo-mundense',
    anniversary: '17 de novembro',
    mayor: 'Casciano Martins Reis',
    averageFormalSalary: 2400,
    formalJobs: 2200,
    urbanizedAreaKm2: 10,
  },
  {
    id: 5106322,
    name: 'Novo Santo Antônio',
    population: 2005,
    population15to44: 842,
    averageIncome: 2100,
    urbanizationIndex: 0.55,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'santo-antoniense',
    anniversary: '29 de setembro',
    mayor: 'Cleomenes Junior Dias Costa',
    averageFormalSalary: 2000,
    formalJobs: 300,
    urbanizedAreaKm2: 3,
  },
  {
    id: 5106330,
    name: 'Novo São Joaquim',
    population: 4945,
    population15to44: 2077,
    averageIncome: 2500,
    urbanizationIndex: 0.76,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'são-joaquinense',
    anniversary: '13 de maio',
    mayor: 'Leonardo Faria Zampa',
    averageFormalSalary: 2300,
    formalJobs: 1100,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5106348,
    name: 'Paranaíta',
    population: 11291,
    population15to44: 4742,
    averageIncome: 2700,
    urbanizationIndex: 0.68,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'paranaitense',
    anniversary: '19 de junho',
    mayor: 'Osmar Antonio Moreira',
    averageFormalSalary: 2500,
    formalJobs: 3100,
    urbanizedAreaKm2: 12,
  },
  {
    id: 5106371,
    name: 'Paranatinga',
    population: 26423,
    population15to44: 11098,
    averageIncome: 3000,
    urbanizationIndex: 0.82,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'paranatinguense',
    anniversary: '17 de dezembro',
    mayor: 'Antonio Marcos Thomazini',
    averageFormalSalary: 2800,
    formalJobs: 6700,
    urbanizedAreaKm2: 22,
  },
  {
    id: 5106422,
    name: 'Pedra Preta',
    population: 17351,
    population15to44: 7287,
    averageIncome: 2800,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'pedra-pretense',
    anniversary: '13 de maio',
    mayor: 'Iraci Ferreira De Souza',
    averageFormalSalary: 2650,
    formalJobs: 4200,
    urbanizedAreaKm2: 15,
  },
  {
    id: 5106505,
    name: 'Planalto da Serra',
    population: 2873,
    population15to44: 1206,
    averageIncome: 2300,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'plan-altense',
    anniversary: '10 de dezembro',
    mayor: 'Natal Alves De Assis Sobrinho',
    averageFormalSalary: 2150,
    formalJobs: 500,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5106653,
    name: 'Poconé',
    population: 31247,
    population15to44: 13124,
    averageIncome: 2300,
    urbanizationIndex: 0.83,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'poconeano',
    anniversary: '21 de janeiro',
    mayor: 'Jonas Eduardo De Queiroz Moraes',
    averageFormalSalary: 2200,
    formalJobs: 5500,
    urbanizedAreaKm2: 20,
  },
  {
    id: 5106703,
    name: 'Pontal do Araguaia',
    population: 7265,
    population15to44: 3051,
    averageIncome: 2600,
    urbanizationIndex: 0.90,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'pontalense',
    anniversary: '20 de dezembro',
    mayor: 'Adelcino Francisco Lopo',
    averageFormalSalary: 2400,
    formalJobs: 1500,
    urbanizedAreaKm2: 6,
  },
  {
    id: 5106752,
    name: 'Ponte Branca',
    population: 1576,
    population15to44: 662,
    averageIncome: 2200,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'ponte-branquense',
    anniversary: '10 de dezembro',
    mayor: 'Clenei Parreira Da Silva',
    averageFormalSalary: 2050,
    formalJobs: 300,
    urbanizedAreaKm2: 3,
  },
  {
    id: 5107040,
    name: 'Porto Alegre do Norte',
    population: 14197,
    population15to44: 5963,
    averageIncome: 2600,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'porto-alegrense',
    anniversary: '13 de maio',
    mayor: 'Carlos Roberto Tomazetto',
    averageFormalSalary: 2450,
    formalJobs: 3300,
    urbanizedAreaKm2: 13,
  },
  {
    id: 5107107,
    name: 'Porto dos Gaúchos',
    population: 5413,
    population15to44: 2273,
    averageIncome: 2700,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'porto-gauchense',
    anniversary: '11 de novembro',
    mayor: 'Vanderlei Antonio De Abreu',
    averageFormalSalary: 2500,
    formalJobs: 1400,
    urbanizedAreaKm2: 9,
  },
  {
    id: 5107156,
    name: 'Porto Esperidião',
    population: 10110,
    population15to44: 4246,
    averageIncome: 2400,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'esperidiense',
    anniversary: '13 de maio',
    mayor: 'Odirlei Queiroz Faria',
    averageFormalSalary: 2200,
    formalJobs: 2500,
    urbanizedAreaKm2: 11,
  },
  {
    id: 5107180,
    name: 'Porto Estrela',
    population: 2758,
    population15to44: 1158,
    averageIncome: 2300,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'porto-estrelense',
    anniversary: '13 de maio',
    mayor: 'Marcio Rodrigues Da Silva',
    averageFormalSalary: 2100,
    formalJobs: 600,
    urbanizedAreaKm2: 6,
  },
  {
    id: 5107248,
    name: 'Poxoréu',
    population: 15091,
    population15to44: 6338,
    averageIncome: 2400,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'poxorense',
    anniversary: '24 de outubro',
    mayor: 'Luciano Hudson Sol Da Costa',
    averageFormalSalary: 2250,
    formalJobs: 3300,
    urbanizedAreaKm2: 12,
  },
  {
    id: 5107297,
    name: 'Querência',
    population: 26769,
    population15to44: 11243,
    averageIncome: 3400,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'querenciano',
    anniversary: '19 de dezembro',
    mayor: 'Gilmar Reinoldo Wentz',
    averageFormalSalary: 3100,
    formalJobs: 7200,
    urbanizedAreaKm2: 23,
  },
  {
    id: 5107354,
    name: 'Reserva do Cabaçal',
    population: 2439,
    population15to44: 1024,
    averageIncome: 2200,
    urbanizationIndex: 0.60,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'cabaçalense',
    anniversary: '13 de maio',
    mayor: 'Jonas Campos Vieira',
    averageFormalSalary: 2050,
    formalJobs: 400,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5107404,
    name: 'Ribeirão Cascalheira',
    population: 10183,
    population15to44: 4277,
    averageIncome: 2500,
    urbanizationIndex: 0.73,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'cascalheirense',
    anniversary: '3 de maio',
    mayor: 'Elza Divina Borges Gomes',
    averageFormalSalary: 2350,
    formalJobs: 2100,
    urbanizedAreaKm2: 10,
  },
  {
    id: 5107578,
    name: 'Ribeirãozinho',
    population: 2263,
    population15to44: 950,
    averageIncome: 2200,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'ribeirãozinhense',
    anniversary: '20 de dezembro',
    mayor: 'Danilo Coelho Domingos',
    averageFormalSalary: 2050,
    formalJobs: 400,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5107255,
    name: 'Rio Branco',
    population: 4627,
    population15to44: 1943,
    averageIncome: 2400,
    urbanizationIndex: 0.81,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'rio-branquense',
    anniversary: '13 de maio',
    mayor: 'Pabollo Victor Batista Siman',
    averageFormalSalary: 2200,
    formalJobs: 900,
    urbanizedAreaKm2: 7,
  },
  {
    id: 5107743,
    name: 'Rondolândia',
    population: 3505,
    population15to44: 1472,
    averageIncome: 2500,
    urbanizationIndex: 0.55,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'rondolandense',
    anniversary: '19 de dezembro',
    mayor: 'José Guedes De Souza',
    averageFormalSalary: 2300,
    formalJobs: 700,
    urbanizedAreaKm2: 6,
  },
  {
    id: 5107750,
    name: 'Rosário Oeste',
    population: 15638,
    population15to44: 6568,
    averageIncome: 2400,
    urbanizationIndex: 0.78,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'rosariense',
    anniversary: '25 de junho',
    mayor: 'Mariano Balabam',
    averageFormalSalary: 2250,
    formalJobs: 2800,
    urbanizedAreaKm2: 11,
  },
  {
    id: 5107768,
    name: 'Salto do Céu',
    population: 3267,
    population15to44: 1372,
    averageIncome: 2200,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'saltense',
    anniversary: '19 de dezembro',
    mayor: 'Mauto Teixeira Espindola',
    averageFormalSalary: 2100,
    formalJobs: 500,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5107776,
    name: 'Santa Carmem',
    population: 5066,
    population15to44: 2128,
    averageIncome: 2800,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'carmense',
    anniversary: '19 de dezembro',
    mayor: 'Pablo Liberal Bortolas',
    averageFormalSalary: 2500,
    formalJobs: 1100,
    urbanizedAreaKm2: 6,
  },
  {
    id: 5107792,
    name: 'Santa Cruz do Xingu',
    population: 2664,
    population15to44: 1119,
    averageIncome: 2600,
    urbanizationIndex: 0.60,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'santa-cruzense',
    anniversary: '20 de dezembro',
    mayor: 'Joraildes Soares De Sousa',
    averageFormalSalary: 2400,
    formalJobs: 600,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5107800,
    name: 'Santo Antônio de Leverger',
    population: 15472,
    population15to44: 6498,
    averageIncome: 2300,
    urbanizationIndex: 0.78,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.CENTRO_SUL_MATOGROSSENSE,
    gentilic: 'levergerense',
    anniversary: '13 de junho',
    mayor: 'Francieli Magalhães De Arruda Vieira Pires',
    averageFormalSalary: 2150,
    formalJobs: 3100,
    urbanizedAreaKm2: 12,
  },
  {
    id: 5107800,
    name: 'Santa Rita do Trivelato',
    population: 3672,
    population15to44: 1542,
    averageIncome: 4500,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'trivelatense',
    anniversary: '20 de dezembro',
    mayor: 'Volmir Bassani',
    averageFormalSalary: 4000,
    formalJobs: 1500,
    urbanizedAreaKm2: 7,
  },
  {
    id: 5107859,
    name: 'Santa Terezinha',
    population: 7578,
    population15to44: 3183,
    averageIncome: 2300,
    urbanizationIndex: 0.60,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'teresinhense',
    anniversary: '29 de março',
    mayor: 'Thiago Castellan Ribeiro',
    averageFormalSalary: 2150,
    formalJobs: 1200,
    urbanizedAreaKm2: 9,
  },
  {
    id: 5107875,
    name: 'Santo Afonso',
    population: 2510,
    population15to44: 1054,
    averageIncome: 2200,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'santo-afonsense',
    anniversary: '13 de maio',
    mayor: 'Luis Fernando Ferreira Falcão',
    averageFormalSalary: 2050,
    formalJobs: 400,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5107883,
    name: 'Santo Antônio do Leste',
    population: 4894,
    population15to44: 2055,
    averageIncome: 3000,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'santo-antoniense',
    anniversary: '10 de dezembro',
    mayor: 'Miguel Jose Brunetta',
    averageFormalSalary: 2700,
    formalJobs: 1100,
    urbanizedAreaKm2: 6,
  },
  {
    id: 5107883,
    name: 'São Félix do Araguaia',
    population: 11333,
    population15to44: 4760,
    averageIncome: 2500,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'são-felixcense',
    anniversary: '13 de maio',
    mayor: 'Acácio Alves Souza',
    averageFormalSalary: 2300,
    formalJobs: 2800,
    urbanizedAreaKm2: 11,
  },
  {
    id: 5107867,
    name: 'São José do Povo',
    population: 2871,
    population15to44: 1206,
    averageIncome: 2200,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'são-joense',
    anniversary: '19 de dezembro',
    mayor: 'Ivanildo Vilela Da Silva',
    averageFormalSalary: 2050,
    formalJobs: 400,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5107305,
    name: 'São José do Rio Claro',
    population: 21392,
    population15to44: 8985,
    averageIncome: 3100,
    urbanizationIndex: 0.88,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'rio-clarense',
    anniversary: '19 de março',
    mayor: 'Levi Ribeiro',
    averageFormalSalary: 2850,
    formalJobs: 5600,
    urbanizedAreaKm2: 19,
  },
  {
    id: 5107958,
    name: 'São José do Xingu',
    population: 5914,
    population15to44: 2484,
    averageIncome: 2500,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'são-joseense',
    anniversary: '19 de dezembro',
    mayor: 'Sandro Jose Luz Costa',
    averageFormalSalary: 2300,
    formalJobs: 1100,
    urbanizedAreaKm2: 7,
  },
  {
    id: 5107875,
    name: 'São José dos Quatro Marcos',
    population: 18193,
    population15to44: 7641,
    averageIncome: 2600,
    urbanizationIndex: 0.86,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'quatro-marquense',
    anniversary: '15 de junho',
    mayor: 'Jamis Silva Bolandin',
    averageFormalSalary: 2400,
    formalJobs: 4300,
    urbanizedAreaKm2: 17,
  },
  {
    id: 5107982,
    name: 'São Pedro da Cipa',
    population: 4188,
    population15to44: 1759,
    averageIncome: 2300,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'são-pedrense',
    anniversary: '20 de dezembro',
    mayor: 'Eduardo Jose Da Silva Abreu',
    averageFormalSalary: 2150,
    formalJobs: 600,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5107065,
    name: 'Sapezal',
    population: 28944,
    population15to44: 12156,
    averageIncome: 3600,
    urbanizationIndex: 0.87,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'sapezalense',
    anniversary: '19 de setembro',
    mayor: 'Cláudio Jose Scariote',
    averageFormalSalary: 3300,
    formalJobs: 10000,
    urbanizedAreaKm2: 20,
  },
  {
    id: 5107990,
    name: 'Serra Nova Dourada',
    population: 1776,
    population15to44: 746,
    averageIncome: 2200,
    urbanizationIndex: 0.60,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'serra-novense',
    anniversary: '20 de dezembro',
    mayor: 'Elson Farias De Souza',
    averageFormalSalary: 2050,
    formalJobs: 300,
    urbanizedAreaKm2: 3,
  },
  {
    id: 5108055,
    name: 'Tabaporã',
    population: 8645,
    population15to44: 3631,
    averageIncome: 2800,
    urbanizationIndex: 0.75,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'tabaporaense',
    anniversary: '29 de setembro',
    mayor: 'Carlos Eduardo Borchardt',
    averageFormalSalary: 2600,
    formalJobs: 2000,
    urbanizedAreaKm2: 10,
  },
  {
    id: 5108105,
    name: 'Tapurah',
    population: 14380,
    population15to44: 6040,
    averageIncome: 3200,
    urbanizationIndex: 0.78,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'tapuraense',
    anniversary: '4 de julho',
    mayor: 'Alvaro Galvan',
    averageFormalSalary: 2900,
    formalJobs: 4100,
    urbanizedAreaKm2: 12,
  },
  {
    id: 5108204,
    name: 'Terra Nova do Norte',
    population: 9946,
    population15to44: 4177,
    averageIncome: 2700,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'terra-novense',
    anniversary: '13 de maio',
    mayor: 'Pascoal Alberton',
    averageFormalSalary: 2500,
    formalJobs: 2500,
    urbanizedAreaKm2: 11,
  },
  {
    id: 5108303,
    name: 'Tesouro',
    population: 3698,
    population15to44: 1553,
    averageIncome: 2300,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'tesourense',
    anniversary: '10 de dezembro',
    mayor: 'João Isaack Moreira Castelo Branco',
    averageFormalSalary: 2100,
    formalJobs: 800,
    urbanizedAreaKm2: 7,
  },
  {
    id: 5108352,
    name: 'Torixoréu',
    population: 3432,
    population15to44: 1441,
    averageIncome: 2400,
    urbanizationIndex: 0.82,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDESTE_MATOGROSSENSE,
    gentilic: 'torixoreense',
    anniversary: '10 de dezembro',
    mayor: 'Thiago Timo Oliveira',
    averageFormalSalary: 2200,
    formalJobs: 900,
    urbanizedAreaKm2: 8,
  },
  {
    id: 5108451,
    name: 'União do Sul',
    population: 3795,
    population15to44: 1594,
    averageIncome: 2600,
    urbanizationIndex: 0.65,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'união-sulense',
    anniversary: '20 de dezembro',
    mayor: 'Vanderlei Antonio De March',
    averageFormalSalary: 2400,
    formalJobs: 900,
    urbanizedAreaKm2: 5,
  },
  {
    id: 5108501,
    name: 'Vale de São Domingos',
    population: 2928,
    population15to44: 1230,
    averageIncome: 2300,
    urbanizationIndex: 0.60,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'dominguense',
    anniversary: '20 de dezembro',
    mayor: 'Leandro Azevedo Da Cunha',
    averageFormalSalary: 2150,
    formalJobs: 500,
    urbanizedAreaKm2: 4,
  },
  {
    id: 5108600,
    name: 'Vera',
    population: 12800,
    population15to44: 5376,
    averageIncome: 3000,
    urbanizationIndex: 0.85,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORTE_MATOGROSSENSE,
    gentilic: 'verense',
    anniversary: '13 de maio',
    mayor: 'Yago Pezarico Giacomelli',
    averageFormalSalary: 2800,
    formalJobs: 3200,
    urbanizedAreaKm2: 13,
  },
  {
    id: 5105507,
    name: 'Vila Bela da Santíssima Trindade',
    population: 16183,
    population15to44: 6797,
    averageIncome: 2500,
    urbanizationIndex: 0.70,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.SUDOESTE_MATOGROSSENSE,
    gentilic: 'vila-belense',
    anniversary: '19 de março',
    mayor: 'Jacob André Bringsken',
    averageFormalSalary: 2300,
    formalJobs: 2800,
    urbanizedAreaKm2: 15,
  },
  {
    id: 5108857,
    name: 'Vila Rica',
    population: 19888,
    population15to44: 8353,
    averageIncome: 2600,
    urbanizationIndex: 0.80,
    status: CityStatus.NotServed,
    mesorregion: Mesorregion.NORDESTE_MATOGROSSENSE,
    gentilic: 'vila-riquense',
    anniversary: '13 de maio',
    mayor: 'João Salomão Pimenta',
    averageFormalSalary: 2400,
    formalJobs: 4500,
    urbanizedAreaKm2: 16,
  }
];

